Q1)

In [68]:
import pandas as pd
pd.__version__

'3.0.6'

In [69]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-28 14:59:30--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.1’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.08s   

2026-09-28 14:59:30 (7.37 MB/s) - ‘car_fuel_efficiency_2026.csv.1’ saved [635180/635180]



---
Q2)

In [70]:
df= pd.read_csv("car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [71]:
len(df)

10000

---
Q3)

In [72]:
print(df['fuel_type'].unique())

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str


In [73]:
print(df['fuel_type'].nunique())

3


---
Q4)

In [74]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

---
Q5)

In [75]:
df1=df[df['origin']=='Asia']
df1['fuel_efficiency_mpg'].max()


np.float64(41.2)

----

Q6)

In [76]:
print(df['horsepower'].median())
print(df['horsepower'].mode())

254.0
0    252.0
Name: horsepower, dtype: float64


In [77]:
df['horsepower']=df['horsepower'].fillna(df['horsepower'].mode())

In [78]:
print(df['horsepower'].median())
print(df['horsepower'].mode())

254.0
0    252.0
Name: horsepower, dtype: float64


------

Q7)

In [79]:
asia=df[df['origin']=='Asia']
print(asia[['vehicle_weight','model_year']].head(7))

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019


In [80]:
print(asia[['vehicle_weight','model_year']].head(7).values)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]


In [81]:
X=asia[['vehicle_weight','model_year']].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [82]:
XTX=X.T@X
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]


In [83]:
import numpy as np
inv=np.linalg.inv(XTX)
inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [84]:
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [85]:
x=inv@X.T
w=x@y
print(w)
sum(w)

[0.13644777 0.2327492 ]


np.float64(0.36919696904925486)